### ISSUE TITLE
CSS paragraph styling error

### ISSUE THREAD

**Issue by FBemf** [jwiegley/git-from-the-bottom-up#22]
There's an issue with how paragraph indents are styled on https://jwiegley.github.io/git-from-the-bottom-up/. There's no CSS in this repo, so I don't know if this is the right place to raise this issue, but there isn't a link anywhere to the repo for the `hamilton.css` stylesheet either.

The default stylesheet indents every paragraph and then removes the indent from the first paragraph child of the parent element, like so:

```css
.main-content p {
    text-indent: 1.5em;
}

.main-content p:first-of-type {
    text-indent: 0;
}
```

The trouble with this is that paragraphs end up being indented after non-paragraph sibling elements, like `<pre></pre>`:

![image](https://user-images.githubusercontent.com/18235755/171700618-84dc4438-8c9b-422d-8361-8b5ec5c1a98c.png)

The fix is to set none of the paragraphs as being indented, and then indent all paragraphs that follow a previous sibling paragraph:

```css
.main-content p {
    text-indent: 0;
}

.main-content p + p {
    text-indent: 1.5 em;
}
```

Which renders like this:

![image](https://user-images.githubusercontent.com/18235755/171701373-819383d6-a6d9-4a00-8ec7-93373095602f.png)
